# Generated by Django 4.1.5 on 2023-01-27 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "business",
            "0003_remove_category_commodity_remove_category_quantity_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
