# Generated by Django 4.1.5 on 2023-01-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_commodity_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
