# Generated by Django 4.1.5 on 2023-01-27 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_alter_commodity_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=255)),
                ('quantity', models.PositiveBigIntegerField()),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.commodity')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_shipments', to='business.warehouse')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_shipments', to='business.warehouse')),
            ],
        ),
    ]
