# Generated by Django 4.1.5 on 2023-01-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "business",
            "0009_shipment_destination_country_shipment_expected_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("In-Transit", "In-Transit"),
                    ("approved", "approved"),
                    ("not-approved", "not-approved"),
                    ("Delivered", "Delivered"),
                ],
                default="not-approved",
                max_length=255,
            ),
        ),
    ]
