# Generated by Django 4.1.5 on 2023-01-28 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0010_alter_shipment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="commodity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="business.commodity",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="quantity",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_shipments",
                to="business.warehouse",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Delivered", "Delivered"),
                    ("approved", "approved"),
                    ("In-Transit", "In-Transit"),
                    ("not-approved", "not-approved"),
                ],
                default="not-approved",
                max_length=255,
            ),
        ),
    ]
